#include "global.h"

int status = 0;
int big_num = 0;
char*day_week[7] = {"Sun","Mon","Tue","Wed","Thus","Fri","Sat"};
char hour = 11;
char minute = 04;
char second = 00   ;
unsigned char day= 7;
char date= 17;
char month= 12;
char year= 22;
unsigned char count = 0;
int format_12h = 0;
int format_24h = 1;
int isPM_or_AM = 1; //PM = 1, AM = 0;
int count1 = 15;

int x = 1;
int y = 0;
int count3 = 0;
unsigned int k = 0;
int num_countries = 5;
int country = 0;
int last_country = 0;
unsigned char* countries[5] = {"Vietnam","China","Moscow","Alaska","London"};
int world_time[5] = {7,8,3,-9,0};
int index_worldtime = 0;
int index_set = 1;
int day_of_month[12] = {31,28,31,30,31,30,31,31,30,31,30,31};
int blink_flag = 0;
int counter[4] ={0,0,0,0};
int turn_counter = 0;
int hour_alarm;
int minute_alarm;
int alarm_flag = 0;
int index_animation = 0;
int animation_menu_size = 2;
//unsigned char* animation_menu[] = {"Man Walking","Wave"};
int index_animation_set = -1;
int flag_animation_menu = 0;
int day_alarm;
int focus[3];
int buzzer_flag = 0;
int index_focus;
int flag_focus_run;
int second_focus;
int flag_alarm_blink = 0;
int flag_press = 0;